"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isAsync = exports.isFunc = exports.identityFn = void 0;
const AsyncFunction = Object.getPrototypeOf(async function () { }).constructor;
const identityFn = (value) => value;
exports.identityFn = identityFn;
const isFunc = (func) => typeof func === "function";
exports.isFunc = isFunc;
const isAsync = (func) => func.constructor.name === AsyncFunction.name;
exports.isAsync = isAsync;
